services:
  - type: web
    runtime: python
    name: flask-app
    repo: https://github.com/GoliathReaper/Assignment_flask
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
    domains:
